spring.datasource.url=jdbc:postgresql://localhost:5432/gentleman_store
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

server.port=8080

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
jwt.expiration=86400100